use anyhow::{Context, Result};
use serde_json::json;
use std::fs;
use std::path::Path;

use crate::output;

const BEGIN_MARKER: &str = "BEGIN MONDAYBOT INTEGRATION";
const END_MARKER: &str = "END MONDAYBOT INTEGRATION";

const AGENTS_CONTENT: &str = r#"### Monday.com Sync (mondaybot)
<!-- Auto-generated by 'mondaybot setup agents' - do not remove these markers -->
<!-- BEGIN MONDAYBOT INTEGRATION -->

This project uses **mondaybot** to sync beads issues with monday.com.

#### Key Principle: Sync is Opt-In
- Only **explicitly linked** issues sync between beads and monday.com
- Running `mondaybot sync update` is always safe — it never creates items, only refreshes linked ones
- Use `mondaybot sync push <beads-id>` to selectively push a beads issue to monday
- Use `mondaybot link add <beads-id> <monday-item-id>` to tie existing items together

#### Quick Reference
```bash
mondaybot doctor                                  # Check setup health
mondaybot boards list                             # List available boards
mondaybot boards get --board-id <id>              # Show board columns/groups (useful for setup)

mondaybot items list                              # List items on configured board
mondaybot items get --item-id <id>                # Get item with sub-items
mondaybot items create --name "Task title"        # Create item on board
mondaybot subitems create --parent-id <id> --name "Sub-task"

mondaybot link add <beads-id> <monday-item-id>    # Link a beads issue to a monday item
mondaybot link list                               # Show all links
mondaybot link remove <beads-id>                  # Unlink

mondaybot sync push <beads-id>                    # Push one issue to monday (creates if new)
mondaybot sync push --epic <beads-id>             # Push epic + child tasks
mondaybot sync pull <monday-item-id>              # Pull one item into beads (creates if new)
mondaybot sync update                             # Refresh all linked items (safe, no creates)
mondaybot sync status                             # Show what's linked and what's drifted
```

#### Workflow
1. PM creates a task in monday.com (or you create one with `mondaybot items create`)
2. Create a matching beads epic: `bd create "Epic title" -t epic`
3. Link them: `mondaybot link add <beads-id> <monday-item-id>`
4. Work on sub-tasks in beads: `bd create "Sub-task" --parent <epic-id>`
5. Push sub-tasks that matter: `mondaybot sync push <sub-task-beads-id>`
6. Keep linked items fresh: `mondaybot sync update`
7. Check drift: `mondaybot sync status`

#### What NOT to do
- Do NOT run a bulk sync of all beads issues — most are internal dev tasks
- Do NOT manually edit `.beads/monday_sync.json` (managed by mondaybot, committed to git)
- Only push issues to monday that are relevant to project tracking

All mondaybot commands output JSON to stdout for programmatic use.

<!-- END MONDAYBOT INTEGRATION -->"#;

const CURSOR_CONTENT: &str = r#"---
alwaysApply: true
---

# Monday.com Sync (mondaybot)
# Auto-generated by 'mondaybot setup cursor' - do not remove these markers
# BEGIN MONDAYBOT INTEGRATION

This project uses **mondaybot** to sync beads issues with monday.com.

## Key Principle: Sync is Opt-In
- Only **explicitly linked** issues sync between beads and monday.com
- Running `mondaybot sync update` is always safe — it never creates items, only refreshes linked ones
- Use `mondaybot sync push <beads-id>` to selectively push a beads issue to monday
- Use `mondaybot link add <beads-id> <monday-item-id>` to tie existing items together

## Quick Reference
```bash
mondaybot doctor                                  # Check setup health
mondaybot boards list                             # List available boards
mondaybot boards get --board-id <id>              # Show board columns/groups (useful for setup)

mondaybot items list                              # List items on configured board
mondaybot items get --item-id <id>                # Get item with sub-items
mondaybot items create --name "Task title"        # Create item on board
mondaybot subitems create --parent-id <id> --name "Sub-task"

mondaybot link add <beads-id> <monday-item-id>    # Link a beads issue to a monday item
mondaybot link list                               # Show all links
mondaybot link remove <beads-id>                  # Unlink

mondaybot sync push <beads-id>                    # Push one issue to monday (creates if new)
mondaybot sync push --epic <beads-id>             # Push epic + child tasks
mondaybot sync pull <monday-item-id>              # Pull one item into beads (creates if new)
mondaybot sync update                             # Refresh all linked items (safe, no creates)
mondaybot sync status                             # Show what's linked and what's drifted
```

## Workflow
1. PM creates a task in monday.com (or you create one with `mondaybot items create`)
2. Create a matching beads epic: `bd create "Epic title" -t epic`
3. Link them: `mondaybot link add <beads-id> <monday-item-id>`
4. Work on sub-tasks in beads: `bd create "Sub-task" --parent <epic-id>`
5. Push sub-tasks that matter: `mondaybot sync push <sub-task-beads-id>`
6. Keep linked items fresh: `mondaybot sync update`
7. Check drift: `mondaybot sync status`

## What NOT to do
- Do NOT run a bulk sync of all beads issues — most are internal dev tasks
- Do NOT manually edit `.beads/monday_sync.json` (managed by mondaybot, committed to git)
- Only push issues to monday that are relevant to project tracking

All mondaybot commands output JSON to stdout for programmatic use.

# END MONDAYBOT INTEGRATION
"#;

/// Insert or replace content between markers in existing text.
/// Returns (new_content, was_replaced).
fn upsert_between_markers(existing: &str, section: &str, begin: &str, end: &str) -> (String, bool) {
    if let (Some(start_idx), Some(end_idx)) = (existing.find(begin), existing.find(end)) {
        let end_of_end = end_idx + existing[end_idx..].find('\n').unwrap_or(end.len());
        let mut result = String::new();
        // Find the start of the line containing BEGIN marker
        let line_start = existing[..start_idx].rfind('\n').map_or(0, |i| i + 1);
        result.push_str(&existing[..line_start]);
        result.push_str(section);
        if !section.ends_with('\n') {
            result.push('\n');
        }
        result.push_str(&existing[end_of_end..]);
        (result, true)
    } else {
        let mut result = existing.to_string();
        if !result.is_empty() && !result.ends_with('\n') {
            result.push('\n');
        }
        if !result.is_empty() {
            result.push('\n');
        }
        result.push_str(section);
        if !result.ends_with('\n') {
            result.push('\n');
        }
        (result, false)
    }
}

pub fn write_agents(dir: &Path) -> Result<()> {
    fs::create_dir_all(dir)
        .with_context(|| format!("failed to create {}", dir.display()))?;
    let file_path = dir.join("AGENTS.md");
    let existing = if file_path.exists() {
        fs::read_to_string(&file_path)
            .with_context(|| format!("failed to read {}", file_path.display()))?
    } else {
        String::new()
    };

    let (new_content, replaced) = upsert_between_markers(
        &existing,
        AGENTS_CONTENT,
        BEGIN_MARKER,
        END_MARKER,
    );

    fs::write(&file_path, &new_content)
        .with_context(|| format!("failed to write {}", file_path.display()))?;

    let action = if replaced {
        "updated"
    } else if existing.is_empty() {
        "created"
    } else {
        "appended"
    };

    output::success(&json!({
        "file": file_path.display().to_string(),
        "action": action,
    }))
}

pub fn write_cursor(dir: &Path) -> Result<()> {
    let cursor_dir = dir.join(".cursor").join("rules");
    fs::create_dir_all(&cursor_dir)
        .with_context(|| format!("failed to create {}", cursor_dir.display()))?;

    let file_path = cursor_dir.join("mondaybot.mdc");
    let existing = if file_path.exists() {
        fs::read_to_string(&file_path)
            .with_context(|| format!("failed to read {}", file_path.display()))?
    } else {
        String::new()
    };

    let (new_content, replaced) = upsert_between_markers(
        &existing,
        CURSOR_CONTENT,
        BEGIN_MARKER,
        END_MARKER,
    );

    fs::write(&file_path, &new_content)
        .with_context(|| format!("failed to write {}", file_path.display()))?;

    let action = if replaced {
        "updated"
    } else if existing.is_empty() {
        "created"
    } else {
        "appended"
    };

    output::success(&json!({
        "file": file_path.display().to_string(),
        "action": action,
    }))
}
